spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/quai_antique"
    username: "user2"
    password: "root"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    database: mysql
    generate-ddl: false


  servlet:
    multipart:
      max-file-size: 10MB